### ISSUE TITLE
"@" symbol in password needs escaped

### ISSUE THREAD

**Issue by bnation** [sasha-alias/sqltabs_tracker#3]
If you try to enter a password with an @ symbol it will be misinterpreted and you cannot login.

**Comment by sasha-alias** [comment]
good catch, thanks.. will get fixed with next release

**Comment by bnation** [comment]
Thanks.  I love the tool so far.  Keep up the good work.

**Comment by sasha-alias** [comment]
v0.4.0 just released
the fix is there together with new feature: history of executed queries
check it out please
